### ISSUE TITLE
Ability to save generated assets

### ISSUE THREAD

**Issue by CuteWaterBeary** [ReinaS-64892/TexTransTool#109]
Hi, I really like what you are doing with this project but I am unable to save any of the assets like the texture atlases. Is there a way to do this?

**Comment by ReinaS-64892** [comment]
Nothing in particular at this point.

Taking out assets... So, by storing them in the Assets folder and being able to handle them universally, do you mean what other non-destructive modification tools ([MA](https://github.com/bdunderscore/modular-avatar), [AAO](https://github.com/anatawa12/AvatarOptimizer)) call "Manual Bake Avatar"?

If so, I would see some value in destructive use of modifications such as atlasing (e.g. [VRM](https://github.com/vrm-c/UniVRM)), as it is needed on platforms other than VRChat.

It seems like a good idea to create a context menu for destructively adapting to AvatarDomainDefinition.

**Comment by CuteWaterBeary** [comment]
Instead of being destructive, making a clone and applying those changes to the clone and unchecking enabled on the original would work really well. 

Multiple reasons for wanting this to exist:
- By not having the assets available in a format that photoshop or any other program can open, it makes it impossible to make any changes after atlassing.
- Checking the generated materials to see if they are what you want them to be.
- No ability to save the model without having this plugin installed and having to rerun the action each time.

**Comment by ReinaS-64892** [comment]
Oh... I forgot to mention,
I'm thinking in the same way as with other tools, to adapt to what you clone.

Most of those reasons make sense and I understand them, but as for the first one, I don't think much about making changes with other tools, because after Atlasizing, the UVs would change drastically.

It's a pain to move the AtlasTexture and other tools to a PNG base so that they can be tweaked by other tools, and VRM and other Unity builds work fine with ".asset" files (VRM does not). (Not in VRM, but on AssetBundle, PNG and ".asset" should be the same in the end.)

Just.... It would be nice to create an option to convert to PNG, etc. when purging an AvatarDomainAsset sub-asset to make it easier to edit.

**Comment by CuteWaterBeary** [comment]
I'm not sure I could implement this but can you give me a hint of where I should look at if I wanted to save the generated assets and what function to use?

**Comment by CuteWaterBeary** [comment]
Also, I gather from what you said that destructive is actually the clone & modify method?

**Comment by ReinaS-64892** [comment]
All of the tool's generators are generated in "Assets/TexTransToolGenerates", but I would like to organize the folders and add a note to the Manual when I create the "Manual Bake Avatar" so that the information is easy to understand.

**Comment by CuteWaterBeary** [comment]
I only see the island cache files in there though...

**Comment by ReinaS-64892** [comment]
These are the future... I wasn't talking about what to do now.

(I should save the "Manual Bake Avatar" and "TexTransToolGenerates" organization for another Issues...)

When using the "AvatarDomainDefinition" preview adaptation, assets are created in "TexTransToolGenerates", but when reverting, these assets are erased.

Conversely, if all components such as "AvatarDomainDefinition" are deleted during preview adaptation, they will not be undone, but the assets will not disappear.

This is quite similar to the "Manual Bake Avatar" that will be implemented in the future.
