### ISSUE TITLE
Questions about what some words mean

### ISSUE THREAD

**Issue by CuteWaterBeary** [ReinaS-64892/TexTransTool#110]
Some of these might be things I don't know or are misspellings but I can't figure out what they are:

- AtralsMaps
- OutOfolag
- TowDMap
- TTG and TTF
- NeaPoint = NearPoint? NewPoint?
- BCS
- VRCBulige = VRCBuild?
- Contenar = Container?
- IsGNTFMP
- nawRenderers
- Souse = Source?

**Comment by ReinaS-64892** [comment]
Sorry for the sometimes messy abbreviation... I will change the names so that they are not abbreviated except for local variables.


AtralsMaps
A misspelling of AtlasMap, a remnant of the former type name of TransMapData.

OutOfolag
You misspelled "out-of-range flag" in various ways.

TowDMap
The name is spelled as "TwoDimensionalMap" because it was intended to be written as "2DMap" and the first digit could not be used.

TTG and TTF
TTG and TTF stand for TexTransGroup and TextureTransformer, respectively.

NeaPoint = NearPoint?
NearPoint. Just a misspelling.

BCS
It stands for barycentric coordinate system.

VRCBulige = VRCBuild?
That's a misspelling of VRCBridge. I was making it to mean bridge, but Build is also fine.

Contenar = Container?
Container is correct.

IsGNTFMP
IsGNTFMP stands for "IsGenerateNewTextureForMergeProperty," but it has been replaced by "PropertyBakeSetting," which is in the code that is no longer in use.

nawRenderers
misspelled "nowRenderers".

Souse = Source?
Source is correct.

**Comment by CuteWaterBeary** [comment]
Thank you so much for clarifying!
