### ISSUE TITLE
SimpleDecal automatically enables preview when switch play mode to edit mode, but the UI doesn't change.

### ISSUE THREAD

**Issue by yelandiealma** [ReinaS-64892/TexTransTool#595]
playmode----->edit mode
RealTimePreview will be enabled automatically, but UI still show "RealTimePreview" .
I need to disable the gameobject which has SimpleDecal and enable it again, then the RealTimePreview will be normal.

TTT 0.8.0-beta.4
NDMF 1.5.0-beta.1

**Comment by ReinaS-64892** [comment]
In the current Beta, NDMF Preview and TTT's traditional RealTimePreview are mixed together, which can be very confusing.

So, it's likely that the automatic operation is due to NDMF Preview, and the RealTimePreview button remaining displayed is normal operation.

We are also planning to change the button display etc. in #593, so please wait until that is merged!

Thanks for reporting!

<details>

<summary>Original Japanese text</summary>

今の Beta では NDMF Preview と TTT 従来の RealTimePreview が混在している状況のため非常に紛らわしい状態です。

なので、おそらく自動的に動作しているのは NDMF Preview によるもので、ボタンの RealTimePreview が表示されたままになっているは通常の動作です。

#593 にてそのあたりのボタン表示等も併せて変更する予定なのでそれがマージするまでお待ちください！

ご報告に感謝します！

</details>
